### ISSUE TITLE
[BUG] The players keep in the arena and no winner

### ISSUE THREAD

**Issue by andris155** [ShaneBeeStudios/HungerGames#77]
**Describe the bug**

The players keep in the arena and no winner

**To Reproduce**

Play HungerGames with v4.15.4 version.

**Expected behavior**

The players no keep in the arena and the last player is the winner.

**Screenshots/Errors**

```
[13:43:05] [Server thread/WARN]: [HungerGames] Task #21686719 for HungerGames v4.15.4 generated an exception
java.lang.NullPointerException: null
	at tk.shanebee.hg.game.GamePlayerData.exit(GamePlayerData.java:382) ~[?:?]
	at tk.shanebee.hg.game.Game.stop(Game.java:304) ~[?:?]
	at tk.shanebee.hg.game.Game.lambda$updateAfterDeath$0(Game.java:399) ~[?:?]
	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:99) ~[patched_1.16.4.jar:git-Yatopia-"2b78178"]
	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[patched_1.16.4.jar:git-Yatopia-"2b78178"]
	at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1370) ~[patched_1.16.4.jar:git-Yatopia-"2b78178"]
	at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:397) ~[patched_1.16.4.jar:git-Yatopia-"2b78178"]
	at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1280) ~[patched_1.16.4.jar:git-Yatopia-"2b78178"]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1011) ~[patched_1.16.4.jar:git-Yatopia-"2b78178"]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:180) ~[patched_1.16.4.jar:git-Yatopia-"2b78178"]
	at java.lang.Thread.run(Unknown Source) [?:?]
```

```
[15:02:38] [Server thread/INFO]: MrZeri issued server command: /hg stop Romos
[15:02:38] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'hg' in plugin HungerGames v4.15.4
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[patched_1.16.4.jar:git-Yatopia-"2b78178"]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.16.4.jar:git-Yatopia-"2b78178"]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchCommand(CraftServer.java:807) ~[patched_1.16.4.jar:git-Yatopia-"2b78178"]
	at net.minecraft.server.v1_16_R3.PlayerConnection.handleCommand(PlayerConnection.java:2035) ~[patched_1.16.4.jar:git-Yatopia-"2b78178"]
	at net.minecraft.server.v1_16_R3.PlayerConnection.c(PlayerConnection.java:1846) ~[patched_1.16.4.jar:git-Yatopia-"2b78178"]
	at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:1799) ~[patched_1.16.4.jar:git-Yatopia-"2b78178"]
	at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:47) ~[patched_1.16.4.jar:git-Yatopia-"2b78178"]
	at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[patched_1.16.4.jar:git-Yatopia-"2b78178"]
	at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:43) ~[patched_1.16.4.jar:git-Yatopia-"2b78178"]
	at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[patched_1.16.4.jar:git-Yatopia-"2b78178"]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:151) ~[patched_1.16.4.jar:git-Yatopia-"2b78178"]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.4.jar:git-Yatopia-"2b78178"]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:114) ~[patched_1.16.4.jar:git-Yatopia-"2b78178"]
	at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1203) ~[patched_1.16.4.jar:git-Yatopia-"2b78178"]
	at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1196) ~[patched_1.16.4.jar:git-Yatopia-"2b78178"]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:125) ~[patched_1.16.4.jar:git-Yatopia-"2b78178"]
	at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1271) ~[patched_1.16.4.jar:git-Yatopia-"2b78178"]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1011) ~[patched_1.16.4.jar:git-Yatopia-"2b78178"]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:180) ~[patched_1.16.4.jar:git-Yatopia-"2b78178"]
	at java.lang.Thread.run(Unknown Source) [?:?]
Caused by: java.lang.NullPointerException
	at tk.shanebee.hg.game.GamePlayerData.exit(GamePlayerData.java:382) ~[?:?]
	at tk.shanebee.hg.game.Game.stop(Game.java:304) ~[?:?]
	at tk.shanebee.hg.commands.StopCmd.run(StopCmd.java:32) ~[?:?]
	at tk.shanebee.hg.commands.BaseCmd.processCmd(BaseCmd.java:54) ~[?:?]
	at tk.shanebee.hg.listeners.CommandListener.onCommand(CommandListener.java:43) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched_1.16.4.jar:git-Yatopia-"2b78178"]
	... 19 more
```

**Version Info:**
 - **Plugin Version:** 4.15.4
 - **Server Version/Platform** Yatopia 1.16.4

**Additional context**

**Comment by kingdomsmp** [comment]
i have the same issue, last player stays in arena and when leaving arena with tp command the arena stays at 1/24 and wont reset

**Comment by ShaneBeee** [comment]
can you please try re-downloading the latest update.
I did a small patch and changed the jar on GitHub.

**Comment by squeaky2137** [comment]
Worked thanks lol
