### ISSUE TITLE
ERROR, any idea how to fix thiss??

### ISSUE THREAD

**Issue by heybangsie** [ShaneBeeStudios/HungerGames#87]
[16:08:29 ERROR]: Could not pass event PlayerDeathEvent to DropHeads v3.5.4
>.... [16:08:29 ERROR]: Suspected Plugins:
>.... [16:08:29 ERROR]: HungerGames{enabled,ver=4.15.5,path=plugins/HungerGames-4.15.5.jar}
>.... [16:08:29 ERROR]: DropHeads{enabled,ver=3.5.4,path=plugins/DropHeads.jar}
>.... [16:08:29 ERROR]: Exception details below:
java.lang.UnsupportedOperationException: null
at java.util.AbstractList.add(AbstractList.java:153) ~[?:?]
at java.util.AbstractList.add(AbstractList.java:111) ~[?:?]
at net.evmodder.DropHeads.listeners.EntityDeathListener.dropHead(EntityDeathListener.java:349) ~[?:?]
at net.evmodder.DropHeads.listeners.EntityDeathListener.onEntityDeath(EntityDeathListener.java:548) ~[?:?]
at net.evmodder.DropHeads.listeners.EntityDeathListener$DeathEventExecutor.execute(EntityDeathListener.java:599) ~[?:?]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[1.16.5-patched.jar:git-Yatopia-ver/1.16.5-18]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[1.16.5-patched.jar:git-Yatopia-ver/1.16.5-18]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:611) ~[1.16.5-patched.jar:git-Yatopia-ver/1.16.5-18]
at tk.shanebee.hg.listeners.GameListener.lambda$processDeath$1(GameListener.java:263) ~[?:?]
at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:99) ~[1.16.5-patched.jar:git-Yatopia-ver/1.16.5-18]
at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:469) ~[1.16.5-patched.jar:git-Yatopia-ver/1.16.5-18]
at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1385) ~[1.16.5-patched.jar:git-Yatopia-ver/1.16.5-18]
at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:397) ~[1.16.5-patched.jar:git-Yatopia-ver/1.16.5-18]
at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1294) ~[1.16.5-patched.jar:git-Yatopia-ver/1.16.5-18]
at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1015) ~[1.16.5-patched.jar:git-Yatopia-ver/1.16.5-18]
at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:175) ~[1.16.5-patched.jar:git-Yatopia-ver/1.16.5-18]
at java.lang.Thread.run(Thread.java:834) [?:?]

**Comment by heybangsie** [comment]
this too 

[16:12:20 ERROR]: Could not pass event BlockPhysicsEvent to HungerGames v4.15.5
>.... [16:12:20 ERROR]: Suspected Plugins: None
>.... [16:12:20 ERROR]: Exception details below:
java.lang.NullPointerException: null
