### ISSUE TITLE
Issue task 2074

### ISSUE THREAD

**Issue by AlexGameQc** [ShaneBeeStudios/HungerGames#9]
The plugin seem to have an issue with paperspigot:

```
[21:53:55]: [WARN] [HungerGames] Task #2074 for HungerGames v4.13.9 generated an exception
java.util.ConcurrentModificationException: null
at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:1042) ~[?:?]
at java.util.ArrayList$Itr.next(ArrayList.java:996) ~[?:?]
at tk.shanebee.hg.tasks.Rollback.run(Rollback.java:33) ~[?:?]
at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.15.2.jar:git-Paper-260]
at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:461) ~[patched_1.15.2.jar:git-Paper-260]
at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1252) ~[patched_1.15.2.jar:git-Paper-260]
at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:430) ~[patched_1.15.2.jar:git-Paper-260]
at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1169) ~[patched_1.15.2.jar:git-Paper-260]
at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:958) ~[patched_1.15.2.jar:git-Paper-260]
at java.lang.Thread.run(Thread.java:834) [?:?]
```

**Comment by ShaneBeee** [comment]
It would have been nice if you didn't delete the template, and actually put some feasible info here.

Ex: When exactly did this error occur? What was happening in the game at the time?
Any info would be nice.

How am I supposed to replicate this if you just delete and ignore the template?

**Comment by AlexGameQc** [comment]
Hi, 
sorry I didn't got the template in the first place, could you paste it here ? 
Sorry about the first post :)

**Comment by AlexGameQc** [comment]
**Describe the bug**
HungerGames 4.13.9 on a Paperspigot version 260 seem to have a conflict with paper and/or multiverse. It spam the console of the same error. 

**To Reproduce**
Create a Hungergame in a multiverse world. 
I changed some setting in [config. ](https://pastebin.com/7hh6ZS38)
And switched the world gamemode to adventure.

List of plugin if needed:
LuckPerms 5.0.72; WorldEdit 7.1.0,8e55131; isSlimeChunk 1.0.1; SAML 2.0.0; PlayerMarkers 0.3.0; LaggRemover 2.0.6; PacketListenerApi 3.7.5-SNAPSHOT; Multiverse-Core 4.1.0-b775; Vivecraft-Spigot-Extensions 1.15.2-r5; HungerGames 4.13.9; Multiverse-Portals 4.1.0-b805; Multiverse-Inventories 3.0.0-b459

**Expected behavior**
No error spam in console

**Screenshots/Errors**
```
[21:53:55]: [WARN] [HungerGames] Task #2074 for HungerGames v4.13.9 generated an exception
java.util.ConcurrentModificationException: null
at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:1042) ~[?:?]
at java.util.ArrayList$Itr.next(ArrayList.java:996) ~[?:?]
at tk.shanebee.hg.tasks.Rollback.run(Rollback.java:33) ~[?:?]
at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.15.2.jar:git-Paper-260]
at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:461) ~[patched_1.15.2.jar:git-Paper-260]
at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1252) ~[patched_1.15.2.jar:git-Paper-260]
at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:430) ~[patched_1.15.2.jar:git-Paper-260]
at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1169) ~[patched_1.15.2.jar:git-Paper-260]
at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:958) ~[patched_1.15.2.jar:git-Paper-260]
at java.lang.Thread.run(Thread.java:834) [?:?]

```
Version Info:
Plugin Version: 4.13.9 (From Spigot)
Server Version/Platform: Paperspigot 260

(Sorry, It was my first time posting for a bug report, I hope this one is better ! )

**Comment by ShaneBeee** [comment]
I will investigate and see if I can fix the issue.
So far I have not been able to replicate.

Based on the error, it tells me which class and line I need look at, but that line seems fine. I might test out a small bug fix, and see if it works.

**Comment by ShaneBeee** [comment]
Can you please try this version and see if it fixes the issue:
https://github.com/ShaneBeeStudios/HungerGames/releases/download/4.13.9.1/HungerGames-4.13.9.1.jar

**Comment by AlexGameQc** [comment]
Weirdly enough, after the auto-restart, it seem fixed. No issus atm with the new version. Gonna keep you updated if it start again !

**Comment by ShaneBeee** [comment]
This was HOPEFULLY fixed in the latest release.
Please try 4.13.10 and let me know if it has been fixed.

**Comment by ShaneBeee** [comment]
I believe this issue was fixed, but I have not heard a reply from the creator of this issue to double check the matter has been resolved. Closing due to inactivity.
